version = 1

[[analyzers]]
name = "python"
enabled = true

  [analyzers.meta]
  runtime_version = "3.8.x"

[[transformers]]
name = "autopep8"
enabled = true

[[transformers]]
name = "prettier"
enabled = true
